DROP TABLE IF EXISTS supplier_order;

CREATE TABLE supplier_order (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_date DATE DEFAULT now(),
  item INTEGER REFERENCES item(id) NOT NULL,
  amount numeric,
  total_cost numeric,
  shipping_status TEXT
);